if( IS_DIRECTORY /i2bm )
  message( STATUS "Add specific paths for CEA - I2BM research labs" )
  execute_process( COMMAND systemIdentification RESULT_VARIABLE result OUTPUT_VARIABLE output OUTPUT_STRIP_TRAILING_WHITESPACE )
  if( result EQUAL 0 )
    list( FIND CMAKE_PREFIX_PATH "/i2bm/research/${output}" result )
    if( result EQUAL -1 )
      set( CMAKE_PREFIX_PATH ${CMAKE_PREFIX_PATH} "/i2bm/research/${output}" )
    endif()
  endif()
endif()