sudo: false
language: python
matrix:
  include:
    - python: 3.8
      dist: xenial  # required for Python >= 3.7
    - python: 3.7
      dist: xenial  # required for Python >= 3.7
    - python: 3.6
    - python: 3.5
    - python: 3.4
    - python: 2.7
    - name: "Python 3.7.2 on macOS"
      os: osx
      osx_image: xcode10.2  # Python 3.7.2 running on macOS 10.14.3
      language: generic     # 'language: python' is an error on Travis CI macOS
  allow_failures:

install: pip install tox-travis
script: tox
