version: ~> 1.0
os: linux
language: python

jobs:
  include:
    - python: 3.8
      dist: xenial  # required for Python >= 3.7
    - python: 3.7
      dist: xenial  # required for Python >= 3.7
    - python: 3.6
    - python: 3.5
    - python: 3.4
    - python: 2.7
    - name: "Python 3.7.2 on macOS"
      os: osx
      osx_image: xcode10.2  # Python 3.7.2 running on macOS 10.14.3
      language: generic     # 'language: python' is an error on Travis CI macOS
  allow_failures:

install:
    - pip install tox-travis
    - pip install -U sphinx
    - cd doc
    - PYTHONPATH="$PWD/../python:$PYTHONPATH" python -c 'import sys; print(sys.path)'
    - PYTHONPATH="$PWD/../python:$PYTHONPATH" python -c 'import brainvisa.maker.version; print(brainvisa.maker.version)'
    - cd ..
    - if [[  "$TRAVIS_OS_NAME" = "linux" && "$TRAVIS_PYTHON_VERSION" == "3.8" ]]; then cd doc && PATH="$PWD/../bin:$PATH" PYTHONPATH="$PWD/../python:$PYTHONPATH" sphinx-build -b html sphinx build_html  && touch build_html/.nojekyll && cd ..; fi
    - if [[ -n "$GITHUB_ACCESS_TOKEN" ]]; then export PUSH_DOC_TO_GH_PAGES=yes; fi

script: tox

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  target-branch: gh-pages
  local-dir: doc/build_html
  on:
    branch: master
    condition: $PUSH_DOC_TO_GH_PAGES == yes && $TRAVIS_OS_NAME == linux && $TRAVIS_PYTHON_VERSION == 3.8
