IF( QWT_FOUND )
ELSE ( QWT_FOUND )

FIND_PATH( QWT_INCLUDE_DIR qwt.h )
FIND_LIBRARY( QWT_LIBRARY qwt )

SET(QWT_FOUND FALSE)

IF(QWT_INCLUDE_DIR AND QWT_LIBRARY)

  SET(QWT_FOUND TRUE)
  
ENDIF(QWT_INCLUDE_DIR AND QWT_LIBRARY)


IF(NOT QWT_FOUND)
  IF(NOT QWT_FIND_QUIETLY)
    MESSAGE(STATUS "Qwt was not found.")
  ELSE(NOT QWT_FIND_QUIETLY)
    IF(QWT_FIND_REQUIRED)
      MESSAGE(FATAL_ERROR "Qwt was not found.")
    ENDIF(QWT_FIND_REQUIRED)
  ENDIF(NOT QWT_FIND_QUIETLY)
ENDIF(NOT QWT_FOUND)


ENDIF( QWT_FOUND )
