# Find GCC
#
# GCC_FOUND
# GCC_LIBRARIES - the gcc library

IF(GCC_LIBRARIES)
  # already found  
  SET(GCC_FOUND TRUE)
ELSE(GCC_LIBRARIES)
  FIND_LIBRARY( GCC_LIBRARIES gcc_s )
  IF(GCC_LIBRARIES)
    SET(GCC_FOUND TRUE)
  ELSE(GCC_LIBRARIES)
    SET(GCC_FOUND FALSE)
      
    IF( GCC_FIND_REQUIRED )
        MESSAGE( SEND_ERROR "GCC was not found." )
    ENDIF( GCC_FIND_REQUIRED )
    IF(NOT GCC_FIND_QUIETLY)
        MESSAGE(STATUS "GCC was not found.")
    ENDIF(NOT GCC_FIND_QUIETLY)
  ENDIF(GCC_LIBRARIES)

ENDIF(GCC_LIBRARIES)

