# Find LIBGCC
#
# LIBGCC_FOUND
# LIBGCC_LIBRARIES - the gcc library

IF(LIBGCC_LIBRARIES)
  # already found  
  SET(LIBGCC_FOUND TRUE)
ELSE()
  FIND_LIBRARY( LIBGCC_LIBRARIES gcc_s )
  IF(LIBGCC_LIBRARIES)
    SET(LIBGCC_FOUND TRUE)
  ELSE()
    SET(LIBGCC_FOUND FALSE)
      
    IF( LIBGCC_FIND_REQUIRED )
        MESSAGE( SEND_ERROR "LIBGCC was not found." )
    ENDIF()
    IF(NOT LIBGCC_FIND_QUIETLY)
        MESSAGE(STATUS "LIBGCC was not found.")
    ENDIF()
  ENDIF()

ENDIF()

