# Find LibSSL
#
# LIBSSL_FOUND
# LIBSSL_LIBRARIES - ssl and crypto libraries

IF(LIBSSL_LIBRARIES)
  # already found  
  SET(LIBSSL_FOUND TRUE)
ELSE()
  FIND_LIBRARY(OPENSSL_LIBRARIES ssl)
  FIND_LIBRARY( CRYPTO_LIBRARY crypto )
  
  IF (WIN32 )
    IF( NOT OPENSSL_LIBRARIES )
      BRAINVISA_FIND_FSENTRY( OPENSSL_LIBRARIES PATTERNS "libssl*" PATHS $ENV{LD_LIBRARY_PATH} )
    ENDIF()
    IF( NOT CRYPTO_LIBRARY )
      BRAINVISA_FIND_FSENTRY( CRYPTO_LIBRARY PATTERNS "libcrypto*" PATHS $ENV{LD_LIBRARY_PATH} )
    ENDIF()
  ENDIF()
  
  IF(OPENSSL_LIBRARIES AND CRYPTO_LIBRARY)
    SET(LIBSSL_LIBRARIES ${OPENSSL_LIBRARIES} "${CRYPTO_LIBRARY}")
    SET(LIBSSL_LIBRARIES ${LIBSSL_LIBRARIES} CACHE PATH "LibSSL libraries")
    SET(LIBSSL_FOUND TRUE)
  ELSE()
    SET(LIBSSL_FOUND FALSE)
      
    IF( LIBSSL_FIND_REQUIRED )
        MESSAGE( SEND_ERROR "LIBSSL was not found." )
    ENDIF()
    IF(NOT LIBSSL_FIND_QUIETLY)
        MESSAGE(STATUS "LIBSSL was not found.")
    ENDIF()
  ENDIF()

ENDIF()

