find_library( LIBVORBISENC vorbisenc )
if( NOT LIBVORBISENC )
  # find libvorbisenc.so.?
  file( GLOB LIBVORBISENC /usr/lib/x86_64-linux-gnu/libvorbisenc.so.? )
  if( LIBVORBISENC )
    set( LIBVORBISENC "${LIBVORBISENC}" CACHE STRING "libvorbisenc library" FORCE )
  endif()
endif()

function( BRAINVISA_PACKAGING_COMPONENT_INFO component package_name package_maintainer package_version )
  set( ${package_name} ${component} PARENT_SCOPE )
  set( ${package_maintainer} "IFR 49" PARENT_SCOPE )
  # Find version
  set( ${package_version} "0.0.0" PARENT_SCOPE )
  get_filename_component( real "${LIBVORBISENC}" REALPATH )
  string( REGEX MATCH "^.*libvorbisenc${CMAKE_SHARED_LIBRARY_SUFFIX}[.](.*)$" match "${real}" )
  if( match )
    set( ${package_version} "${CMAKE_MATCH_1}" PARENT_SCOPE )
  endif()
endfunction()


function( BRAINVISA_PACKAGING_COMPONENT_RUN component )
  BRAINVISA_THIRDPARTY_DEPENDENCY( "${component}" RUN DEPENDS libvorbis RUN )
  if( LIBVORBISENC )
    BRAINVISA_INSTALL_RUNTIME_LIBRARIES( ${component} "${LIBVORBISENC}" )
    set(${component}_PACKAGED TRUE PARENT_SCOPE)
  else()
    set(${component}_PACKAGED FALSE PARENT_SCOPE)
  endif()
endfunction()
