find_library( LIBASYNCNS asyncns )
if( NOT LIBASYNCNS )
  # find libasyncns.so.?
  file( GLOB LIBASYNCNS /usr/lib/x86_64-linux-gnu/libasyncns.so.? )
  if( LIBASYNCNS )
    set( LIBASYNCNS "${LIBASYNCNS}" CACHE STRING "libasyncns library" FORCE )
  endif()
endif()

function( BRAINVISA_PACKAGING_COMPONENT_INFO component package_name package_maintainer package_version )
  set( ${package_name} ${component} PARENT_SCOPE )
  set( ${package_maintainer} "IFR 49" PARENT_SCOPE )
  # Find version
  set( ${package_version} "0.0.0" PARENT_SCOPE )
  get_filename_component( real "${LIBASYNCNS}" REALPATH )
  string( REGEX MATCH "^.*libasyncns${CMAKE_SHARED_LIBRARY_SUFFIX}[.](.*)$" match "${real}" )
  if( match )
    set( ${package_version} "${CMAKE_MATCH_1}" PARENT_SCOPE )
  endif()
endfunction()


function( BRAINVISA_PACKAGING_COMPONENT_RUN component )
  if( LIBASYNCNS )
    BRAINVISA_INSTALL_RUNTIME_LIBRARIES( ${component} "${LIBASYNCNS}" )
    set(${component}_PACKAGED TRUE PARENT_SCOPE)
  else()
    set(${component}_PACKAGED FALSE PARENT_SCOPE)
  endif()
endfunction()
