# Find specific windows iconv package
FIND_PATH(LIBICONV_INCLUDE_DIR NAMES iconv.h)

FIND_LIBRARY(LIBICONV_LIBRARIES NAMES iconv)

# handle the QUIETLY and REQUIRED arguments and set LIBICONV_FOUND to TRUE if 
# all listed variables are TRUE
INCLUDE(FindPackageHandleStandardArgs)
FIND_PACKAGE_HANDLE_STANDARD_ARGS(LibIconv DEFAULT_MSG LIBICONV_LIBRARIES LIBICONV_INCLUDE_DIR)

MARK_AS_ADVANCED(LIBICONV_INCLUDE_DIR LIBICONV_LIBRARIES)

